# Generated by Django 3.2.4 on 2021-06-18 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biologs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogPost',
            new_name='BiologPost',
        ),
    ]
